
import java.awt.Point;


public class JFrameARCH extends javax.swing.JFrame {

    
    
    public JFrameARCH() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regFLAGS = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        regA = new javax.swing.JTextField();
        regPC = new javax.swing.JTextField();
        nextINSTR = new javax.swing.JTextField();
        regU = new javax.swing.JTextField();
        regS = new javax.swing.JTextField();
        regB = new javax.swing.JTextField();
        regDP = new javax.swing.JTextField();
        V = new javax.swing.JLabel();
        Z = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        I = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        regX = new javax.swing.JTextField();
        regY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        titlejLabel = new javax.swing.JLabel();

        regFLAGS.setEditable(false);
        regFLAGS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regFLAGS.setForeground(new java.awt.Color(0, 0, 255));
        regFLAGS.setText("0");
        regFLAGS.setPreferredSize(new java.awt.Dimension(100, 27));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ARCHETICTURE");
        setLocation(new java.awt.Point(5, 150));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regA.setEditable(false);
        regA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regA.setForeground(new java.awt.Color(0, 0, 255));
        regA.setText("0");
        regA.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel1.add(regA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        regPC.setEditable(false);
        regPC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regPC.setForeground(new java.awt.Color(0, 0, 255));
        regPC.setText("00");
        jPanel1.add(regPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 90, 30));

        nextINSTR.setEditable(false);
        nextINSTR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nextINSTR.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(nextINSTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, 185, 30));

        regU.setEditable(false);
        regU.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regU.setForeground(new java.awt.Color(0, 0, 255));
        regU.setText("0");
        regU.setPreferredSize(new java.awt.Dimension(72, 27));
        jPanel1.add(regU, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 100, -1, -1));

        regS.setEditable(false);
        regS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regS.setForeground(new java.awt.Color(0, 0, 255));
        regS.setText("0");
        regS.setMinimumSize(new java.awt.Dimension(73, 27));
        regS.setPreferredSize(new java.awt.Dimension(73, 27));
        jPanel1.add(regS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        regB.setEditable(false);
        regB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regB.setForeground(new java.awt.Color(0, 0, 255));
        regB.setText("0");
        regB.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel1.add(regB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        regDP.setEditable(false);
        regDP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regDP.setForeground(new java.awt.Color(0, 0, 255));
        regDP.setText("0");
        regDP.setPreferredSize(new java.awt.Dimension(45, 30));
        jPanel1.add(regDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 280, -1, -1));

        V.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        V.setForeground(new java.awt.Color(0, 0, 255));
        V.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        V.setText("0");
        V.setRequestFocusEnabled(false);
        jPanel1.add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 20, 30));

        Z.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Z.setForeground(new java.awt.Color(0, 0, 255));
        Z.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Z.setText("0");
        Z.setRequestFocusEnabled(false);
        jPanel1.add(Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 280, 20, 30));

        N.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        N.setForeground(new java.awt.Color(0, 0, 255));
        N.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        N.setText("0");
        N.setRequestFocusEnabled(false);
        jPanel1.add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 20, 30));

        I.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        I.setForeground(new java.awt.Color(0, 0, 255));
        I.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        I.setText("0");
        I.setRequestFocusEnabled(false);
        jPanel1.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 20, 30));

        H.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        H.setForeground(new java.awt.Color(0, 0, 255));
        H.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        H.setText("0");
        H.setRequestFocusEnabled(false);
        jPanel1.add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 20, 30));

        F.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        F.setForeground(new java.awt.Color(0, 0, 255));
        F.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        F.setText("0");
        F.setRequestFocusEnabled(false);
        jPanel1.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 20, 30));

        E.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        E.setForeground(new java.awt.Color(0, 0, 255));
        E.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        E.setText("0");
        E.setRequestFocusEnabled(false);
        jPanel1.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 20, 30));

        C.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        C.setForeground(new java.awt.Color(0, 0, 255));
        C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C.setText("0");
        C.setRequestFocusEnabled(false);
        jPanel1.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 20, 30));

        regX.setEditable(false);
        regX.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regX.setForeground(new java.awt.Color(0, 0, 255));
        regX.setText("0");
        regX.setPreferredSize(new java.awt.Dimension(73, 25));
        jPanel1.add(regX, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 345, -1, -1));

        regY.setEditable(false);
        regY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regY.setForeground(new java.awt.Color(0, 0, 255));
        regY.setText("0");
        regY.setBorder(null);
        regY.setPreferredSize(new java.awt.Dimension(73, 25));
        jPanel1.add(regY, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 345, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Architechture.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 349));
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 349));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 349));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        titlejLabel.setBackground(new java.awt.Color(255, 255, 255));
        titlejLabel.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(153, 153, 153));
        titlejLabel.setText("Architecture");
        titlejLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titlejLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlejLabelMouseDragged(evt);
            }
        });
        titlejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlejLabelMousePressed(evt);
            }
        });
        jPanel1.add(titlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Point init;
    private void titlejLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlejLabelMousePressed
        // TODO add your handling code here:
        init = evt.getPoint();
                getComponentAt(init);
    }//GEN-LAST:event_titlejLabelMousePressed

    private void titlejLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlejLabelMouseDragged
        // TODO add your handling code here:
        int deltaX = evt.getXOnScreen() - init.x;
                int deltaY = evt.getYOnScreen() - init.y;
                setLocation(deltaX,deltaY);
    }//GEN-LAST:event_titlejLabelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameARCH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameARCH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel C;
    public javax.swing.JLabel E;
    public javax.swing.JLabel F;
    public javax.swing.JLabel H;
    public javax.swing.JLabel I;
    public javax.swing.JLabel N;
    public javax.swing.JLabel V;
    public javax.swing.JLabel Z;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField nextINSTR;
    public javax.swing.JTextField regA;
    public javax.swing.JTextField regB;
    public javax.swing.JTextField regDP;
    public javax.swing.JTextField regFLAGS;
    public javax.swing.JTextField regPC;
    public javax.swing.JTextField regS;
    public javax.swing.JTextField regU;
    public javax.swing.JTextField regX;
    public javax.swing.JTextField regY;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
