/**
 *
 * @author MOUADILI
 */
public class MAIN extends javax.swing.JFrame {
    
    

    public static JFrameEDITOR editor=new JFrameEDITOR();
    public static RAM ra = new RAM();
    public static Programme prog = new Programme();
    public static ROM ro = new ROM();
    public static JFrameARCH arch = new JFrameARCH();
    public static APropos apropos = new APropos();

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
        //testFLAGS
        registreCC.testAZN(arch);
        registreCC.testBZN(arch);
        //Initiation de arch
         arch.regPC.setText(ro.model.getValueAt(0, 0).toString());
         arch.regS.setText(String.format("%04X", 0));
         arch.regU.setText(String.format("%04X", 0));
         arch.regA.setText(String.format("%02X", 0));
         arch.regB.setText(String.format("%02X", 0));
         arch.regX.setText(String.format("%04X", 0));
         arch.regY.setText(String.format("%04X", 0));
         arch.regDP.setText(String.format("%02X", 0));
         //charger la base de donnee des instructions
         CONTENU.remplirImmediat();
         CONTENU.remplirInherent();
         CONTENU.remplirDirect();
         CONTENU.remplirIndexe();
         arch.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tstimme = new javax.swing.JButton();
        tstinher = new javax.swing.JButton();
        tstdire = new javax.swing.JButton();
        tstRUN = new javax.swing.JButton();
        tstPASAPAS = new javax.swing.JButton();
        tstINDEXE = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        stepjButton3 = new javax.swing.JButton();
        runjButton4 = new javax.swing.JButton();
        undojButton5 = new javax.swing.JButton();
        resetjButton6 = new javax.swing.JButton();
        EXITjButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichierMenu = new javax.swing.JMenu();
        nouveauItem = new javax.swing.JMenuItem();
        QuitterItem = new javax.swing.JMenuItem();
        fenetrsMenu = new javax.swing.JMenu();
        ProgrammeCHBox = new javax.swing.JCheckBoxMenuItem();
        RAMCHBox = new javax.swing.JCheckBoxMenuItem();
        ROMCHBox = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ArrangerItem = new javax.swing.JMenuItem();
        aideMenu = new javax.swing.JMenu();
        APropos = new javax.swing.JMenuItem();

        tstimme.setText("IMME");
        tstimme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstimmeActionPerformed(evt);
            }
        });

        tstinher.setText("inher");
        tstinher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstinherActionPerformed(evt);
            }
        });

        tstdire.setText("direct");
        tstdire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstdireActionPerformed(evt);
            }
        });

        tstRUN.setText("RUN");
        tstRUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstRUNActionPerformed(evt);
            }
        });

        tstPASAPAS.setText("pas a pas");
        tstPASAPAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstPASAPASActionPerformed(evt);
            }
        });

        tstINDEXE.setText("jButton1");
        tstINDEXE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstINDEXEActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOTO6809 by ASKA");
        setIconImages(null);
        setResizable(false);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-document.png"))); // NOI18N
        newButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        jPanel2.add(newButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editing.png"))); // NOI18N
        editButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel2.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        stepjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/footsteps.png"))); // NOI18N
        stepjButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stepjButton3.setEnabled(false);
        stepjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepjButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(stepjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        runjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/running.png"))); // NOI18N
        runjButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        runjButton4.setEnabled(false);
        runjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runjButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(runjButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        undojButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo.png"))); // NOI18N
        undojButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        undojButton5.setEnabled(false);
        undojButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undojButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(undojButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        resetjButton6.setText("RESET");
        resetjButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resetjButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(resetjButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        EXITjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/opened-door-aperture.png"))); // NOI18N
        EXITjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EXITjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITjButtonActionPerformed(evt);
            }
        });
        jPanel2.add(EXITjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 770, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 70));

        fichierMenu.setText("Fichier");

        nouveauItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        nouveauItem.setText("nouveau");
        nouveauItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauItemActionPerformed(evt);
            }
        });
        fichierMenu.add(nouveauItem);

        QuitterItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        QuitterItem.setText("Quitter");
        QuitterItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterItemActionPerformed(evt);
            }
        });
        fichierMenu.add(QuitterItem);

        jMenuBar1.add(fichierMenu);

        fenetrsMenu.setText("Fenêtres");

        ProgrammeCHBox.setText("Programme");
        ProgrammeCHBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProgrammeCHBoxItemStateChanged(evt);
            }
        });
        fenetrsMenu.add(ProgrammeCHBox);

        RAMCHBox.setText("RAM");
        RAMCHBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RAMCHBoxItemStateChanged(evt);
            }
        });
        fenetrsMenu.add(RAMCHBox);

        ROMCHBox.setText("ROM");
        ROMCHBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ROMCHBoxItemStateChanged(evt);
            }
        });
        fenetrsMenu.add(ROMCHBox);
        fenetrsMenu.add(jSeparator1);

        ArrangerItem.setText("Arranger");
        ArrangerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrangerItemActionPerformed(evt);
            }
        });
        fenetrsMenu.add(ArrangerItem);

        jMenuBar1.add(fenetrsMenu);

        aideMenu.setText("Aide");

        APropos.setText("A propos...");
        APropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AProposActionPerformed(evt);
            }
        });
        aideMenu.add(APropos);

        jMenuBar1.add(aideMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nouveauItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauItemActionPerformed
        // TODO add your handling code here:
        editor.dispose();
        editor = new JFrameEDITOR();
        editor.setVisible(true);
       
    }//GEN-LAST:event_nouveauItemActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        editor.dispose();
        editor = new JFrameEDITOR();
        editor.setVisible(true);
        editor.editorTextArea.requestFocusInWindow();
    }//GEN-LAST:event_newButtonActionPerformed

    private void EXITjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITjButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_EXITjButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        editor.setVisible(true);
        editor.editorTextArea.requestFocusInWindow();
    }//GEN-LAST:event_editButtonActionPerformed

    private void QuitterItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_QuitterItemActionPerformed

    private void RAMCHBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_RAMCHBoxItemStateChanged
        // TODO add your handling code here:
        if(RAMCHBox.isSelected()){
            ra.setVisible(true);
        }else{
            ra.dispose();
        }
    }//GEN-LAST:event_RAMCHBoxItemStateChanged

    private void ROMCHBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ROMCHBoxItemStateChanged
        // TODO add your handling code here:
         if(ROMCHBox.isSelected()){
            ro.setVisible(true);
        }else{
            ro.dispose();
        }
    }//GEN-LAST:event_ROMCHBoxItemStateChanged

    private void ProgrammeCHBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProgrammeCHBoxItemStateChanged
        // TODO add your handling code here:
        if(ProgrammeCHBox.isSelected()){
            prog.setVisible(true);
        }else{
            prog.dispose();
        }
    }//GEN-LAST:event_ProgrammeCHBoxItemStateChanged

    private void ArrangerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrangerItemActionPerformed
        // Arranger
        ra.setLocation(420, 150);
        ro.setLocation(570, 150);
        prog.setLocation(210, 150);
        arch.setLocation(new java.awt.Point(5, 150));
    }//GEN-LAST:event_ArrangerItemActionPerformed

    private void tstimmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstimmeActionPerformed
        // TODO add your handling code here:
        String[] line = editor.editorTextArea.getText().split("\n");
        instr.adrImmediat(arch, ro, ra, line[0]);
    }//GEN-LAST:event_tstimmeActionPerformed

    private void tstinherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstinherActionPerformed
        // TODO add your handling code here:
         String[] line = editor.editorTextArea.getText().split("\n");
        instr.adrInherent(arch, ro, ra, line[0]);
    }//GEN-LAST:event_tstinherActionPerformed

    private void tstdireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstdireActionPerformed
        // TODO add your handling code here:
        String[] line = editor.editorTextArea.getText().split("\n");
        instr.adrDirect(arch, ro, ra, line[0]);
    }//GEN-LAST:event_tstdireActionPerformed

    private void AProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AProposActionPerformed
        // TODO add your handling code here:
        apropos.setVisible(true);
    }//GEN-LAST:event_AProposActionPerformed

    private void tstRUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstRUNActionPerformed
        // TODO add your handling code here:
                instr.traiterLigne(editor.editorTextArea.getText());

    }//GEN-LAST:event_tstRUNActionPerformed

    private void tstPASAPASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstPASAPASActionPerformed
        // TODO add your handling code here:
        instr.traiterLinePrLine(editor.editorTextArea.getText());
    }//GEN-LAST:event_tstPASAPASActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        //Iconifier tous
        int etat = this.getExtendedState();
        arch.setExtendedState(etat);
        editor.setExtendedState(etat);
        ro.setExtendedState(etat);
        ra.setExtendedState(etat);
        prog.setExtendedState(etat);
    }//GEN-LAST:event_formWindowStateChanged

    private void stepjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepjButton3ActionPerformed
        // TODO add your handling code here:
        instr.traiterLinePrLine(editor.editorTextArea.getText());
        if(instr.p!=0)undojButton5.setEnabled(true);
    }//GEN-LAST:event_stepjButton3ActionPerformed

    private void runjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runjButton4ActionPerformed
        // TODO add your handling code here:
        instr.traiterLigne(editor.editorTextArea.getText());
    }//GEN-LAST:event_runjButton4ActionPerformed

    private void undojButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undojButton5ActionPerformed
        // TODO add your handling code here:
        instr.traiterUndo(editor.editorTextArea.getText());
        if(instr.p<=0)undojButton5.setEnabled(false);
        stepjButton3.setEnabled(true);
        runjButton4.setEnabled(true);
    }//GEN-LAST:event_undojButton5ActionPerformed

    private void resetjButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButton6ActionPerformed
        // RESET
        arch.regPC.setText(ro.model.getValueAt(0, 0).toString());
         arch.regS.setText(String.format("%04X", 0));
         arch.regU.setText(String.format("%04X", 0));
         arch.regA.setText(String.format("%02X", 0));
         arch.regB.setText(String.format("%02X", 0));
         arch.regX.setText(String.format("%04X", 0));
         arch.regY.setText(String.format("%04X", 0));
         arch.regDP.setText(String.format("%02X", 0));
         //premier instr
        String[] line = editor.editorTextArea.getText().split("\n");
        arch.nextINSTR.setText(line[0].toUpperCase());
        instr.p=0;
        stepjButton3.setEnabled(true);
        runjButton4.setEnabled(true);
        undojButton5.setEnabled(false);
        //ram rom prog
        ra.dispose();
        ro.dispose();
        prog.dispose();
        RAMCHBox.setSelected(false);
        ROMCHBox.setSelected(false);
        ProgrammeCHBox.setSelected(false);
        ra=new RAM();
        //ro=new ROM();
        //prog=new Programme();
    }//GEN-LAST:event_resetjButton6ActionPerformed

    private void tstINDEXEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstINDEXEActionPerformed
        // TODO add your handling code here:
        String[] line = editor.editorTextArea.getText().split("\n");
        instr.adrIndexe(arch, ro, ra, line[0]);
    }//GEN-LAST:event_tstINDEXEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MAIN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem APropos;
    private javax.swing.JMenuItem ArrangerItem;
    private javax.swing.JButton EXITjButton;
    public static javax.swing.JCheckBoxMenuItem ProgrammeCHBox;
    private javax.swing.JMenuItem QuitterItem;
    public static javax.swing.JCheckBoxMenuItem RAMCHBox;
    public static javax.swing.JCheckBoxMenuItem ROMCHBox;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JButton editButton;
    private javax.swing.JMenu fenetrsMenu;
    private javax.swing.JMenu fichierMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JButton newButton;
    private javax.swing.JMenuItem nouveauItem;
    private javax.swing.JButton resetjButton6;
    public static javax.swing.JButton runjButton4;
    public static javax.swing.JButton stepjButton3;
    private javax.swing.JButton tstINDEXE;
    private javax.swing.JButton tstPASAPAS;
    private javax.swing.JButton tstRUN;
    private javax.swing.JButton tstdire;
    private javax.swing.JButton tstimme;
    private javax.swing.JButton tstinher;
    public static javax.swing.JButton undojButton5;
    // End of variables declaration//GEN-END:variables

   
}
