
import java.awt.Point;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Programme extends javax.swing.JFrame {

    /**
     * Creates new form Programme
     */
    public Programme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prgTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(210, 150));
        setName("frameProg"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlejLabel.setBackground(new java.awt.Color(255, 255, 255));
        titlejLabel.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(153, 153, 153));
        titlejLabel.setText("Programme");
        titlejLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titlejLabel.setMaximumSize(new java.awt.Dimension(154, 17));
        titlejLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlejLabelMouseDragged(evt);
            }
        });
        titlejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlejLabelMousePressed(evt);
            }
        });
        jPanel1.add(titlejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 355));

        prgTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prgTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        prgTable.setDoubleBuffered(true);
        prgTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prgTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        prgTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(prgTable);
        if (prgTable.getColumnModel().getColumnCount() > 0) {
            prgTable.getColumnModel().getColumn(0).setResizable(false);
            prgTable.getColumnModel().getColumn(0).setPreferredWidth(80);
            prgTable.getColumnModel().getColumn(1).setResizable(false);
            prgTable.getColumnModel().getColumn(1).setPreferredWidth(170);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 240));
        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Point init;
    private void titlejLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlejLabelMouseDragged
        // TODO add your handling code here:
        int deltaX = evt.getXOnScreen() - init.x;
        int deltaY = evt.getYOnScreen() - init.y;
        setLocation(deltaX,deltaY);
    }//GEN-LAST:event_titlejLabelMouseDragged

    private void titlejLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlejLabelMousePressed
        // TODO add your handling code here:
        init = evt.getPoint();
        getComponentAt(init);
    }//GEN-LAST:event_titlejLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable prgTable;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
